#!/usr/bin/env python3
"""
make_frozen_xrefs.py — freeze the live xr cross-references for submission.

The working pair
    P1_bernoulli_20260701_Bernoulli_revised.tex        (main)
    P1_bernoulli_supp_20260701_Bernoulli_revised.tex   (supplement)
cross-reference each other by reading each other's .aux at compile time, which
requires the companion's .aux at compile time.  Journal submission systems
compile each file in isolation, so before submitting run:

    pdflatex  <both files, until stable>
    python3   make_frozen_xrefs.py

This writes *_frozen.tex copies in which the xr lines are replaced by an
inlined block of \\csname r@...\\endcsname definitions taken from the fresh
companion .aux — each frozen file then compiles standalone.  The working
.tex files are not modified.
"""

import re
import sys
from pathlib import Path

MAIN = "P1_bernoulli_20260701_Bernoulli_revised"
SUPP = "P1_bernoulli_supp_20260701_Bernoulli_revised"


def aux_labels(aux):
    labels = {}
    for line in Path(aux + ".aux").read_text().splitlines():
        m = re.match(r"\\newlabel\{([^}]+)\}\{(\{.*\})\}$", line)
        if m and "@cref" not in m.group(1):
            labels[m.group(1)] = m.group(2)
    return labels


def local_labels(tex):
    return set(re.findall(r"\\label\{([^}]+)\}", Path(tex + ".tex").read_text()))


def referenced(tex):
    src = Path(tex + ".tex").read_text()
    keys = set()
    for m in re.finditer(r"\\(?:ref|eqref|pageref|autoref)\{([^}]+)\}", src):
        keys.add(m.group(1))
    return keys


def freeze(tex, companion):
    src = Path(tex + ".tex").read_text()
    pat = re.compile(
        r"\\makeatletter\n\\newcommand\{\\inputcompanionaux\}.*?"
        r"\\inputcompanionaux\{" + re.escape(companion) + r"\}\n\\makeatother",
        re.DOTALL)
    if not pat.search(src):
        sys.exit(f"{tex}.tex: companion-aux block not found — already frozen?")
    external = sorted(referenced(tex) - local_labels(tex))
    labels = aux_labels(companion)
    lines = ["% Frozen cross-references (generated by make_frozen_xrefs.py",
             f"%   from {companion}.aux — do not edit by hand)",
             "\\makeatletter"]
    missing = []
    for key in external:
        if key in labels:
            lines.append(
                f"\\expandafter\\def\\csname r@{key}\\endcsname{{{labels[key]}}}")
        else:
            missing.append(key)
    lines.append("\\makeatother")
    if missing:
        sys.exit(f"{tex}.tex: labels missing from {companion}.aux: {missing}\n"
                 "Recompile the companion and re-run.")
    out = Path(tex + "_frozen.tex")
    block = "\n".join(lines)
    out.write_text(pat.sub(lambda _: block, src))
    print(f"wrote {out}  ({len(external)} frozen labels)")


if __name__ == "__main__":
    freeze(MAIN, SUPP)
    freeze(SUPP, MAIN)
    print("Frozen copies compile standalone; submit those, keep editing the originals.")
